(() => {
  'use strict';
  const cfg=window.LUNAVISUAL_CONFIG||{}, $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let sb, session, connections=[];
  const label={youtube:'YouTube',tiktok:'TikTok',twitch:'Twitch'};
  function status(msg,bad=false){const e=$('pageStatus');e.textContent=msg;e.className=`status ${bad?'bad':'ok'}`}
  async function auth(){sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'lunavisual-auth-v2'}});const r=await sb.auth.getSession();session=r.data.session;if(!session){location.href='profile.html?next=creators.html';throw new Error('login_required')}}
  function renderConnection(provider){const c=connections.find(x=>x.provider===provider), host=$(`${provider}Connection`);if(!host)return;if(!c){host.innerHTML='<span class="muted">Не подключён</span>';return}const warning=c.suspicious?'<span class="tag warn">Нужна ручная проверка</span>':'<span class="tag ok">Проверено</span>';host.innerHTML=`<div class="row"><img class="avatar" src="${esc(c.avatar_url||'lunavisual-logo.png')}" alt=""><div><strong>${esc(c.display_name||c.handle||label[provider])}</strong><div class="small muted">ID: ${esc(c.provider_user_id)}</div><div class="small">Подписчики: <b>${Number(c.follower_count||0).toLocaleString('ru-RU')}</b> · качество ${Number(c.quality_score||0)}/100</div>${warning}</div></div>`}
  async function load(){const cr=await sb.from('creator_connections').select('*').eq('user_id',session.user.id).order('created_at');if(cr.error)throw cr.error;connections=cr.data||[];['youtube','tiktok','twitch'].forEach(renderConnection);const ar=await sb.from('creator_applications').select('id,provider,requested_rank,status,follower_count_at_apply,quality_score_at_apply,review_note,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false});if(ar.error)throw ar.error;$('appsList').innerHTML=(ar.data||[]).length?(ar.data||[]).map(a=>`<div class="provider"><div><strong>${esc(label[a.provider])} → ${esc(a.requested_rank)}</strong><div class="small muted">${new Date(a.created_at).toLocaleString('ru-RU')} · подписчиков: ${Number(a.follower_count_at_apply).toLocaleString('ru-RU')} · качество: ${Number(a.quality_score_at_apply)}/100</div>${a.review_note?`<div class="small">Комментарий: ${esc(a.review_note)}</div>`:''}</div><span class="tag ${a.status==='approved'?'ok':a.status==='rejected'?'bad':'moon'}">${esc(a.status)}</span></div>`).join(''):'<div class="muted">Заявок пока нет.</div>'}
  async function invoke(name,body){const r=await fetch(`${cfg.supabaseUrl}/functions/v1/${name}`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',apikey:cfg.supabasePublishableKey},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
  async function connect(provider){status(`Подготовка OAuth ${label[provider]}…`);const j=await invoke('creator-oauth-start',{provider});location.href=j.url}
  async function refresh(provider){status(`Проверяем ${label[provider]}…`);await invoke('creator-verify',{provider});await load();status(`${label[provider]} обновлён.`)}
  async function apply(provider){const c=connections.find(x=>x.provider===provider);if(!c){status(`Сначала подключите ${label[provider]}.`,true);return}const note=prompt('Комментарий к заявке (необязательно):','')||'';const {data,error}=await sb.rpc('submit_lunavisual_creator_application',{p_provider:provider,p_note:note});if(error)throw error;if(!data?.ok){const msg={not_enough_followers:`Недостаточно подписчиков: ${data.current||0} из ${data.required||0}.`,verification_outdated:'Обновите проверку аккаунта.',manual_review_required:'Автопроверка заметила аномалии. Обновите статистику или обратитесь к администратору.'}[data?.error]||data?.error||'Не удалось отправить заявку';status(msg,true);return}await load();status('Заявка отправлена администратору.')}
  async function disconnect(provider){if(!connections.some(x=>x.provider===provider)){status(`${label[provider]} уже отключён.`);return}if(!confirm(`Отключить ${label[provider]} от LunaVisual? Серверный OAuth-токен и связь аккаунта будут удалены.`))return;const {error}=await sb.rpc('disconnect_lunavisual_creator_provider',{p_provider:provider});if(error)throw error;await load();status(`${label[provider]} отключён.`)}
  async function boot(){try{await auth();const q=new URLSearchParams(location.search);if(q.get('connected'))status(`${label[q.get('connected')]||q.get('connected')} успешно подключён.`);if(q.get('oauth_error'))status(`OAuth: ${q.get('oauth_error')}`,true);await load();document.querySelectorAll('[data-connect]').forEach(b=>b.onclick=()=>connect(b.dataset.connect).catch(e=>status(e.message,true)));document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=()=>refresh(b.dataset.refresh).catch(e=>status(e.message,true)));document.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>apply(b.dataset.apply).catch(e=>status(e.message,true)));document.querySelectorAll('[data-disconnect]').forEach(b=>b.onclick=()=>disconnect(b.dataset.disconnect).catch(e=>status(e.message,true)))}catch(e){if(e.message!=='login_required')status(e.message,true)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
